"use strict";
exports.__esModule = true;
exports.OffchainMerkleMap = exports.OffchainMerkleStorage = exports.NULLIFIER_MERKLE_MAP = exports.TASKS_MERKLE_MAP = exports.CREDENTIALS_MERKLE_MAP = exports.CLAIMS_MERKLE_MAP = exports.PLANS_MERKLE_MAP = exports.MEMBERS_MERKLE_MAP = exports.PERSONS_MERKLE_MAP = exports.COMMUNITIES_MERKLE_MAP = void 0;
var offchain_merkle_storage_js_1 = require("./offchain-merkle-storage.js");
exports.OffchainMerkleStorage = offchain_merkle_storage_js_1.OffchainMerkleStorage;
var offchain_merkle_map_js_1 = require("./offchain-merkle-map.js");
exports.OffchainMerkleMap = offchain_merkle_map_js_1.OffchainMerkleMap;
var PERSONS_MERKLE_MAP = 1;
exports.PERSONS_MERKLE_MAP = PERSONS_MERKLE_MAP;
var COMMUNITIES_MERKLE_MAP = 2;
exports.COMMUNITIES_MERKLE_MAP = COMMUNITIES_MERKLE_MAP;
var MEMBERS_MERKLE_MAP = 3;
exports.MEMBERS_MERKLE_MAP = MEMBERS_MERKLE_MAP;
var PLANS_MERKLE_MAP = 4;
exports.PLANS_MERKLE_MAP = PLANS_MERKLE_MAP;
var CLAIMS_MERKLE_MAP = 5;
exports.CLAIMS_MERKLE_MAP = CLAIMS_MERKLE_MAP;
var TASKS_MERKLE_MAP = 6;
exports.TASKS_MERKLE_MAP = TASKS_MERKLE_MAP;
var CREDENTIALS_MERKLE_MAP = 7;
exports.CREDENTIALS_MERKLE_MAP = CREDENTIALS_MERKLE_MAP;
var NULLIFIER_MERKLE_MAP = 8;
exports.NULLIFIER_MERKLE_MAP = NULLIFIER_MERKLE_MAP;
